### PR TITLE
fix: vault-log-level overwritten in pods

### LINKED ISSUE #290: webhook: VAULT_LOG_LEVEL overwritten in Pods
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
`VAULT_LOG_LEVEL` env is overwritten in Pods according to the webhook's own `LOG_LEVEL`. This prevents engineers from managing vault-env's default verbosity independently when admins need to troubleshoot issues at the webhook itself, for example by setting `LOG_LEVEL` to `debug`.

**Expected behaviour**:
I expected the config that manages the webhook's logging to be independent from the config that manages the default log level injected in Pod's for vault-env.

**Steps to reproduce the bug**:
Steps to reproduce the bug should be clear and easily reproducible to help people
gain an understanding of the problem.

1. Set `LOG_LEVEL` in the webhook's env to `debug`
2. Create the Pod, see that its `VAULT_LOG_LEVEL` env gets set to `debug`

**Additional context**:

Looks like the config is loaded here:

https://github.com/banzaicloud/bank-vaults/blob/dcdd0c5eb81648259e8f034024a84b61c5ecd7ab/pkg/webhook/config.go#L280-L284

And then it's injected in the Pod here:

https://github.com/banzaicloud/bank-vaults/blob/dcdd0c5eb81648259e8f034024a84b61c5ecd7ab/pkg/webhook/pod.go#L347-L354

And it's also used to configure the webhook's logger:

https://github.com/banzaicloud/bank-vaults/blob/dcdd0c5eb81648259e8f034024a84b61c5ecd7ab/cmd/vault-secrets-webhook/main.go#L75-L79

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.22
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- bank-vaults version (e.g. 0.4.17): 1.13.0
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): N/A
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

### PR DESCRIPTION
**Pull request by csatib02**
## Overview

- Wrote a test to showcase the problem mentioned in the issue.
- Added a check, if `VAULT_LOG_LEVEL` is set in the container, it remains unchanged after mutation. However, if it isn't, and the `vaultConfig` contains the relevant field, the value is set accordingly.

Fixes #290

### CODE REVIEW

File: pkg/webhook/pod.go [hunk 1]
```diff
@@ -358,7 +358,8 @@ func (mw *MutatingWebhook) mutateContainers(ctx context.Context, containers []co
 			})
 		}
 
-		if vaultConfig.LogLevel != "" {
+		ok := isLogLevelSet(container.Env)
+		if !ok && vaultConfig.LogLevel != "" {
```
Comment (ramizpolic) [inline pkg/webhook/pod.go:362]:
```suggestion
		if !isLogLevelSet(container.Env) && vaultConfig.LogLevel != "" {
```

**Review by akijakya — APPROVED** [review]
LGTM!

**Review by ramizpolic — APPROVED** [review]
LGTM!
